[project]
name = "mblog"
version = "0.0.1"
description = "A micro blog website built using django."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
